### ISSUE TITLE
Please add function to add more keepalived nodes

### ISSUE THREAD

**Issue by LaneaLucy** [goabout/kube-keepalived-vip#1]
I want to be able to use keepalived in kubernetes together with a external keepalived so in case the entire cluster is offline, i still have a backup service that reacts to the vip.
Ideally there would be another config map key, which value is added after the clusterNodes variable [here](https://github.com/goabout/kube-keepalived-vip/blob/ad6b2566099c9ad2b756a71d9fa80adcef92c6ab/controller.go#L350)

**Comment by SAGV** [comment]
Hi @LaneaLucy,
Unfortunately, we do not actively maintain this repo anymore and currently do not have enough dev power to implement any improvements. I recommend forking the repo and implementing it yourself. 😢
